<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOpvqnzt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOpvqnzt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOpvqnzt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOpvqnzt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOpvqnzt\appProdProjectContainer(array(
    'container.build_hash' => 'Opvqnzt',
    'container.build_id' => '7ba448a2',
    'container.build_time' => 1715093450,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOpvqnzt');
