services:
  _defaults:
    public: true

  ##############
  # Your Module

  bonaicontent.module:
    class: bonaicontent
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'bonaicontent'

  bonaicontent.context:
    class: Context
    factory: ['Context', 'getContext']

  #####################
  # PrestaShop Account
  bonaicontent.ps_accounts_installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    arguments:
      - '5.0'

  bonaicontent.ps_accounts_facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    arguments:
      - '@bonaicontent.ps_accounts_installer'
        #####################
  # PrestaShop Billing

  bonaicontent.ps_billings_context_wrapper:
    class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    arguments:
      - '@bonaicontent.ps_accounts_facade'
      - '@bonaicontent.context'
      - false

  bonaicontent.ps_billings_facade:
    class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
    public: true
    arguments:
      - '@bonaicontent.ps_billings_context_wrapper'
      - '@bonaicontent.module'

  bonaicontent.ps_billings_service:
    class: 'PrestaShopCorp\Billing\Services\BillingService'
    public: true
    arguments:
      - '@bonaicontent.ps_billings_context_wrapper'
      - '@bonaicontent.module'
