<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXbpiald\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXbpiald/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXbpiald.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXbpiald\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXbpiald\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xbpiald',
    'container.build_id' => 'dca5256f',
    'container.build_time' => 1716310423,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXbpiald');
